// Attached to every AI run's output (see orchestrator.js) — the one
// piece of text that must never be dropped, no matter which agent ran
// or which provider produced it. Kept in one place so it can't drift
// between agents, and so it's trivial to audit that every code path
// that returns AI output actually includes it.

export const AI_OUTPUT_DISCLAIMER =
  'This content was generated by an AI assistant and has not been verified. ' +
  'It may be incomplete or contain factual errors, and it does not guarantee ' +
  '100% accuracy of any vehicle condition, history, or risk assessment. A ' +
  'human admin must review this output before it is used in any report or ' +
  'sent to a customer.';

// Short form for UI badges/labels where the full sentence doesn't fit
// (e.g. a small tag next to an AI-drafted section in admin-reports.html,
// if that integration is used — see that page for where this shows up).
export const AI_OUTPUT_DISCLAIMER_SHORT = 'AI-drafted — not verified, requires human review.';
